del help\assets\dependents-info-1.png /f 
del help\assets\charts_quadrant_example_new.png /f 
del help\assets\sendreview.png /f 
del help\assets\useacrxasset.png /f 
del help\assets\gradleconsole.png /f 
del help\assets\upload_package.jpg /f 
del help\assets\agentuitabs.png /f 
del help\assets\ad-1.png /f 
del help\assets\agentuicontenttab.png /f 
del help\assets\img17.png /f 
del help\assets\06-apply-rules-to-adaptive-form_main.png /f 
del help\assets\1_elementstext.png /f 
del help\assets\search-with-predicates.png /f 
del help\assets\auto_sync_options_new.png /f 
del help\assets\web_configuration_console_new.png /f 
del help\assets\conversion-in-progress.png /f 
del help\assets\enrollment_application.png /f 
del help\assets\whencustomeridischanged.png /f 
del help\assets\drag-n-drop-lf.png /f 
del help\assets\balancedright.png /f 
del help\assets\health_benefits.png /f 
del help\assets\beryl.png /f 
del help\assets\fdm_ad.png /f 
del help\assets\statictableproperties-1.png /f 
del help\assets\webchannelassets.png /f 
del help\assets\ipad.png /f 
del help\assets\insurance-form-on-mobile.png /f 
del help\assets\ic_web_hyperlink_new.png /f 
del help\assets\image-in-adaptive-form.png /f 
del help\assets\list_view_view_dropdown.jpg /f 
del help\assets\appliedruletext.png /f 
del help\assets\newly-created-adaptive-form.png /f 
del help\assets\create-af-2.png /f 
del help\assets\data_display_patterns_ssn_new.png /f 
del help\assets\we-finance-home.png /f 
del help\assets\useradmin-creditcard.png /f 
del help\assets\claimsubrogationlayout.png /f 
del help\assets\upgrade-websphere-livecycle-es3.pdf /f 
del help\assets\using-autosave-freq-06.png /f 
del help\assets\img2.png /f 
del help\assets\capture_new.png /f 
del help\assets\login-ssn.png /f 
del help\assets\weretail-schema.png /f 
del help\assets\form-data-model_l.png /f 
del help\assets\components.zip /f 
del help\assets\eclipsebuildmws.png /f 
del help\assets\textbackgroundcolor.png /f 
del help\assets\layout_fragment_print_text_field.png /f 
del help\assets\3_contentexplorernewnode_customlogo.png /f 
del help\assets\dropobjectstooutputfield-retrievedata.png /f 
del help\assets\upgrade-weblogic.pdf /f 
del help\assets\img3.png /f 
del help\assets\approval-enrolment-kit-email.png /f 
del help\assets\insertfdmelementtext.png /f 
del help\assets\bill_details_customerplan_fdm.png /f 
del help\assets\analytics_new.png /f 
del help\assets\workflow_aem.png /f 
del help\assets\aem6forms_download.png /f 
del help\assets\johnjacobsaeminbox.png /f 
del help\assets\default-submit-form.png /f 
del help\assets\toolbarselection.png /f 
del help\assets\forms_designer_subform_new.png /f 
del help\assets\drop-down_customization.png /f 
del help\assets\package_share_icon.jpg /f 
del help\assets\docfragoptions.png /f 
del help\assets\auto-insurance-renewal-email.png /f 
del help\assets\img13.png /f 
del help\assets\create-interactive-communication.png /f 
del help\assets\tranquil-1.png /f 
del help\assets\ab-test-report-3.png /f 
del help\assets\apply-addon-card.png /f 
del help\assets\install-cluster-websphere.pdf /f 
del help\assets\summary_charges_static_new.png /f 
del help\assets\revertinheritance.png /f 
del help\assets\formsetinprocessmgmt2.png /f 
del help\assets\chart_basicproperties.png /f 
del help\assets\0configmanager.png /f 
del help\assets\aem_forms_-_recommendedtopology.png /f 
del help\assets\assets-browser-content-only.png /f 
del help\assets\desktop.png /f 
del help\assets\table_ic_web_new.png /f 
del help\assets\variable_bill_details_static_text_new.png /f 
del help\assets\09-style%20your%20adaptive%20form_small.png /f 
del help\assets\mortgage-analytics.png /f 
del help\assets\edit-error-state.png /f 
del help\assets\conversion-graph.png /f 
del help\assets\remotefunction.png /f 
del help\assets\aftia-start-conversion.jpg /f 
del help\assets\create-a-workflow-pdf.png /f 
del help\assets\folders.png /f 
del help\assets\create-a-theme.png /f 
del help\assets\SimpleMediumIC.zip /f 
del help\assets\ab-test-report.png /f 
del help\assets\wegov_adobe_analytics.jpg /f 
del help\assets\accessibility.png /f 
del help\assets\typeofformattingtoolbar.png /f 
del help\assets\expense-report-approved.png /f 
del help\assets\sidebar-comps-1.png /f 
del help\assets\analytics_key_metrics.jpg /f 
del help\assets\mws-content-1.png /f 
del help\assets\publish-cmp-assets-1.png /f 
del help\assets\aem-forms-workflow-on-osgi-.png /f 
del help\assets\we-finance-home-1.png /f 
del help\assets\pastetextmsword-2.png /f 
del help\assets\correspondence-management.png /f 
del help\assets\create_first_ic_web_template.png /f 
del help\assets\test_data_model.png /f 
del help\assets\topology_for_usinghtmlworkspaceandformsapp.png /f 
del help\assets\forms-with-fields-placed-nearby.png /f 
del help\assets\mws-content-2.png /f 
del help\assets\lf_preview.png /f 
del help\assets\listitems.png /f 
del help\assets\george_lang-1.png /f 
del help\assets\analytics_data.jpg /f 
del help\assets\createformset2.png /f 
del help\assets\layout_fragment_print_repeat_new.png /f 
del help\assets\sarahrosejoininglettersign2.png /f 
del help\assets\gen-settings-2.png /f 
del help\assets\newtabui.png /f 
del help\assets\sign_document_new.png /f 
del help\assets\functionchart.png /f 
del help\assets\diagram1.png /f 
del help\assets\typekit-to-adobe-fonts.png /f 
del help\assets\attachments-app.png /f 
del help\assets\sync-app.png /f 
del help\assets\createapppackageswizard2.png /f 
del help\assets\johndoeadditionalinformationreview-copy.png /f 
del help\assets\3_content.png /f 
del help\assets\1_repeat.png /f 
del help\assets\adaptiveformdata.png /f 
del help\assets\install-single-server-jboss.pdf /f 
del help\assets\pre-filled-form.png /f 
del help\assets\insurance-contract-email.png /f 
del help\assets\sample_chart_web_new.png /f 
del help\assets\undo_redo_actions_new.png /f 
del help\assets\icon_resize.png /f 
del help\assets\expandededitrulevariables.png /f 
del help\assets\cc-application-form-desktop.png /f 
del help\assets\specialcharacters-1.png /f 
del help\assets\cancel_inheritance_web_channel_new.png /f 
del help\assets\cancelinheritance.png /f 
del help\assets\using-designer.pdf /f 
del help\assets\tranquil.png /f 
del help\assets\workbench-installation-overview.png /f 
del help\assets\aem-forms-workspace.jpg /f 
del help\assets\s2.png /f 
del help\assets\textbackgroundcolorapplied-1.png /f 
del help\assets\specialcharactersinlinemodule.png /f 
del help\assets\johnjacobstaskdetail-1.png /f 
del help\assets\layout_fragment_print_text_field_new.png /f 
del help\assets\aem6forms_paste.png /f 
del help\assets\save-as-draft-update-operation.png /f 
del help\assets\structure_configure_policy_new.png /f 
del help\assets\desktopview.png /f 
del help\assets\placeholder_elements_in_xmldata.png /f 
del help\assets\functions_charts_new.png /f 
del help\assets\reenableinheritance.png /f 
del help\assets\liberty-1.png /f 
del help\assets\default-watermark.png /f 
del help\assets\upgrade-turnkey-livecycle-es3.pdf /f 
del help\assets\linkages.png /f 
del help\assets\webchannelpreview.png /f 
del help\assets\surface_transaction_reporting.png /f 
del help\assets\home-screen-1-1.png /f 
del help\assets\create-ic.png /f 
del help\assets\expressionbuilder.png /f 
del help\assets\aftia-accessibility-report.jpg /f 
del help\assets\style-data-capture-components.png /f 
del help\assets\eclipse-screenshot.png /f 
del help\assets\sample-data.png /f 
del help\assets\dropobjectstoinputfield-retrievedata.png /f 
del help\assets\capture.png /f 
del help\assets\asset-1.png /f 
del help\assets\mortgage-workflow-model.png /f 
del help\assets\close-icon.svg /f 
del help\assets\topology.png /f 
del help\assets\tabspaces.png /f 
del help\assets\bill_summary_static.png /f 
del help\assets\1.png /f 
del help\assets\forms-portal-page.png /f 
del help\assets\access.png /f 
del help\assets\createformset1.png /f 
del help\assets\dynamic.xdp.zip /f 
del help\assets\renewal_reminder_email.png /f 
del help\assets\custom-configuration-parameters.png /f 
del help\assets\template_logos.jpg /f 
del help\assets\expense-report-inbox.png /f 
del help\assets\2_1_enterdata.png /f 
del help\assets\pastetexteditablemodule-1.png /f 
del help\assets\pastetexttextmodule.png /f 
del help\assets\configure_services_customer_new.png /f 
del help\assets\in-form-signing-experience.png /f 
del help\assets\workflow.png /f 
del help\assets\createconditionscreenrulesadded.png /f 
del help\assets\sidebar-comps-3.png /f 
del help\assets\lettertab.png /f 
del help\assets\add_association_new.png /f 
del help\assets\submission-actions.png /f 
del help\assets\save-as-draft-getall-operation.png /f 
del help\assets\reevaluation.png /f 
del help\assets\createcorrespondenceproperties.png /f 
del help\assets\03-create-adaptive-form-%20main-image_small.png /f 
del help\assets\dropobjectstoinputfield-updatedata.png /f 
del help\assets\1-1.png /f 
del help\assets\aftia-review-properties.jpg /f 
del help\assets\selectassetpath.png /f 
del help\assets\camila_santos-1.png /f 
del help\assets\attachmentsagentui.png /f 
del help\assets\review-results.png /f 
del help\assets\johndoeadditionainformationinbox.png /f 
del help\assets\new_columns_display.jpg /f 
del help\assets\transform.png /f 
del help\assets\customer_details_df2.png /f 
del help\assets\aem-forms-app.png /f 
del help\assets\translation_json_in_fr.png /f 
del help\assets\sarahroseemailmoredetails.png /f 
del help\assets\edit_group_settings.jpg /f 
del help\assets\dynamictableletter.png /f 
del help\assets\0_1_introscreenshot.png /f 
del help\assets\2_selection.png /f 
del help\assets\summary_charges_static_fdm_new.png /f 
del help\assets\5_downloadflatpdf.png /f 
del help\assets\data-source-selection.png /f 
del help\assets\upload-scr.png /f 
del help\assets\agent_ui_email.png /f 
del help\assets\ad-2.png /f 
del help\assets\4_repeat_hoverdetail.png /f 
del help\assets\mortgage-statement-email.png /f 
del help\assets\create-af-1.png /f 
del help\assets\template_editor_initial_content.png /f 
del help\assets\5_edittextmodule.png /f 
del help\assets\specialcharacters.png /f 
del help\assets\toolbar_1.png /f 
del help\assets\aftia-admin-access-edit.jpg /f 
del help\assets\4_highlightmoduleincontent.png /f 
del help\assets\statictableletter.png /f 
del help\assets\createformset3.png /f 
del help\assets\content_tree_root_panel_new.png /f 
del help\assets\assigntask-metadata.png /f 
del help\assets\resume-1.png /f 
del help\assets\link.png /f 
del help\assets\propertiesattachments.png /f 
del help\assets\aftia-conversion-settings-3.jpg /f 
del help\assets\1_bulkapproval.png /f 
del help\assets\activities_tab.png /f 
del help\assets\basic-features.png /f 
del help\assets\scribble.png /f 
del help\assets\keyboard.png /f 
del help\assets\interactive-use-cases-af-cm-osgi-workflow.png /f 
del help\assets\sign_test_document.png /f 
del help\assets\information_to_send_to_report_suite.png /f 
del help\assets\translation_json_in_en.png /f 
del help\assets\layout_fragment_print.png /f 
del help\assets\ref-themes.png /f 
del help\assets\ultramarine-1.png /f 
del help\assets\ruleeditorfdm-1-1.png /f 
del help\assets\create-daptive-form-workflow.png /f 
del help\assets\upgrade-turnkey.pdf /f 
del help\assets\we-retail-logo-text.png /f 
del help\assets\dependencies.png /f 
del help\assets\sarah-ack-email.png /f 
del help\assets\aem-forms-portal.png /f 
del help\assets\aftia-add-css.jpg /f 
del help\assets\textitemstabsitemsoverlaynode1.png /f 
del help\assets\aftia-test-service.jpg /f 
del help\assets\server_options.png /f 
del help\assets\drafts-submissions-edit.png /f 
del help\assets\2_contentexplorernewnode.png /f 
del help\assets\content_tee_all_panels.png /f 
del help\assets\list_view.jpg /f 
del help\assets\mortgage-statement.png /f 
del help\assets\xdpfieldproperties.png /f 
del help\assets\add_association_customer_bills.png /f 
del help\assets\scribble-ui.png /f 
del help\assets\corporate-card-workflow-model.png /f 
del help\assets\8_previewcustomdatafile.png /f 
del help\assets\hidden-fields.gif /f 
del help\assets\af-custom-layout.zip /f 
del help\assets\mortgage-welcome-kit.png /f 
del help\assets\sample_chart_print_column_new.png /f 
del help\assets\gloriainbox-1.png /f 
del help\assets\ic_web_content_tree_new.png /f 
del help\assets\edittextmodule.png /f 
del help\assets\form-editor.png /f 
del help\assets\14_sendletterforreview_lca.png /f 
del help\assets\additionalinformation1.png /f 
del help\assets\keyboard-inapp.png /f 
del help\assets\fields-without-clear-borders.png /f 
del help\assets\ms_dynamics.png /f 
del help\assets\text_fields_table_new.png /f 
del help\assets\relational-database-data-source-configuration.png /f 
del help\assets\bill_summary_static_new.png /f 
del help\assets\employee_self_service_reference_site_new.png /f 
del help\assets\properties_dynamics_crm.jpg /f 
del help\assets\styled-adaptive-form-1.png /f 
del help\assets\ic_web_hyperlink.png /f 
del help\assets\display-validation-error.gif /f 
del help\assets\ab-test-report-2.png /f 
del help\assets\apply_new_template.png /f 
del help\assets\liberty.png /f 
del help\assets\create_child_property_new.png /f 
del help\assets\summary-report.png /f 
del help\assets\inbox-1.png /f 
del help\assets\display.png /f 
del help\assets\pastedtext.png /f 
del help\assets\upgrade-jboss-livecycle.pdf /f 
del help\assets\specialcharacters-2.png /f 
del help\assets\aftia-select-production-configuration.jpg /f 
del help\assets\nobreak.png /f 
del help\assets\toolbar_3.png /f 
del help\assets\attachments-screen.png /f 
del help\assets\configure_smtp.jpg /f 
del help\assets\upgrade-websphere.pdf /f 
del help\assets\chartwebchannel.png /f 
del help\assets\fonteditingtoolbar.png /f 
del help\assets\group.jpg /f 
del help\assets\02.png /f 
del help\assets\assets-docfragments.png /f 
del help\assets\sample_data_cust.png /f 
del help\assets\child-support-analytics-dashboard.png /f 
del help\assets\printweb_2.png /f 
del help\assets\wegov_forms_package.jpg /f 
del help\assets\xsd_root_element_new.png /f 
del help\assets\google_play.png /f 
del help\assets\2_testformproperties.png /f 
del help\assets\configured_data_source.jpg /f 
del help\assets\test3.jpg /f 
del help\assets\cmmetadatapropertiesappsfolder.png /f 
del help\assets\img10.png /f 
del help\assets\upgrade-turnkey-livecycle.pdf /f 
del help\assets\editdeletedownloadafolder.png /f 
del help\assets\retarget-solution.png /f 
del help\assets\img6.png /f 
del help\assets\logconfig.png /f 
del help\assets\azure_directory.png /f 
del help\assets\newtabui-1.png /f 
del help\assets\aftia-reports.jpg /f 
del help\assets\upgrade-weblogic-livecycle-es3.pdf /f 
del help\assets\filling_a_form.png /f 
del help\assets\customtoolbaractiondemo.zip /f 
del help\assets\variable_create_string_new.png /f 
del help\assets\wealth-management.png /f 
del help\assets\classicsimple.png /f 
del help\assets\dense%20form.png /f 
del help\assets\1_aftestregistration.png /f 
del help\assets\textbackgroundcolor-2.png /f 
del help\assets\home-screen-1.png /f 
del help\assets\4_reviewresults.png /f 
del help\assets\crx-default1.png /f 
del help\assets\2_clickrun.png /f 
del help\assets\aya_tan_new.png /f 
del help\assets\gloriariosinbox.png /f 
del help\assets\zip_android_folder_structure.png /f 
del help\assets\submit-rule.png /f 
del help\assets\WorkbenchHelp.pdf /f 
del help\assets\8_pagebreak.png /f 
del help\assets\pictures-002-small.png /f 
del help\assets\1_defaultapp.png /f 
del help\assets\component_toolbar_inherited_web_new.png /f 
del help\assets\search_sidepanel.png /f 
del help\assets\root_subform_print_template.png /f 
del help\assets\signature-step.png /f 
del help\assets\action_toolbar_new.png /f 
del help\assets\shiiping-address-update.png /f 
del help\assets\dontremindmeagainforthisproject.png /f 
del help\assets\sarahroseemailapproval.png /f 
del help\assets\2_conditiondialog.png /f 
del help\assets\upgrade-path-2nd.png /f 
del help\assets\designer_scribble.png /f 
del help\assets\usage_charges_rule_all_new.png /f 
del help\assets\analytics_report.jpg /f 
del help\assets\formsetinprocessmgmt1.png /f 
del help\assets\android_folder_studio.png /f 
del help\assets\search_lister.png /f 
del help\assets\targeting-menu.png /f 
del help\assets\4.png /f 
del help\assets\3-2.png /f 
del help\assets\adobe-analytics-cloud-services.png /f 
del help\assets\aftia-payload-ims-config.jpg /f 
del help\assets\02-create-adaptive-form-main-image.png /f 
del help\assets\thumbnail.png /f 
del help\assets\analytics_report_data_updated.jpg /f 
del help\assets\chart_properties_web_new.png /f 
del help\assets\ab-test-configure.png /f 
del help\assets\styled-adaptive-form.png /f 
del help\assets\interactive_communication.png /f 
del help\assets\runtestcase.png /f 
del help\assets\html-todo-list.png /f 
del help\assets\07-apply-rules-to-adaptive-form_small.png /f 
del help\assets\ab-test-configure-1.png /f 
del help\assets\3.png /f 
del help\assets\create_first_ic_doc_fragments.png /f 
del help\assets\id-arg.png /f 
del help\assets\lock_task.png /f 
del help\assets\aem6forms_panel-html.png /f 
del help\assets\scripting-basics.pdf /f 
del help\assets\unbound_fields_variables_highlights_dc.jpg /f 
del help\assets\prepare-install-single-server.pdf /f 
del help\assets\analytics.png /f 
del help\assets\variable_create_string.png /f 
del help\assets\as_intro_page_extraction.png /f 
del help\assets\opencontentvariables.png /f 
del help\assets\save_as_template.png /f 
del help\assets\action3.png /f 
del help\assets\read-default.png /f 
del help\assets\add_association_argument.png /f 
del help\assets\static.xdp.zip /f 
del help\assets\selectlayout.png /f 
del help\assets\3_repeatdialog.png /f 
del help\assets\classic.png /f 
del help\assets\aftia-quick-access.jpg /f 
del help\assets\gloriaapproves.png /f 
del help\assets\toolbar4.png /f 
del help\assets\1_itemscreatenode.png /f 
del help\assets\aem6forms_add.png /f 
del help\assets\2_defaultappoverlaynode.png /f 
del help\assets\pageinformationad.png /f 
del help\assets\sazanamiminchointext.png /f 
del help\assets\printweb_2-2.png /f 
del help\assets\create_web_template.gif /f 
del help\assets\corporate-card-leave-application-workflow-model.png /f 
del help\assets\0_1_5ioverlaynodedialog.png /f 
del help\assets\aftia-advanced-conversion-settings-wefinance.jpg /f 
del help\assets\blue-chip-pdf.gif /f 
del help\assets\root_subform_designer_new.png /f 
del help\assets\various-stages-of-formx50.gif /f 
del help\assets\start3.png /f 
del help\assets\sidebar-comps-2.png /f 
del help\assets\rule_editor_icon.png /f 
del help\assets\mws-content.png /f 
del help\assets\createruleicon.png /f 
del help\assets\dragndrop.png /f 
del help\assets\aftia-contact-read-service.jpg /f 
del help\assets\edit.svg /f 
del help\assets\jjacobs-inbox-1.png /f 
del help\assets\lf_dragdrop_table.png /f 
del help\assets\summary_charges_static.png /f 
del help\assets\we-finance-home-3.png /f 
del help\assets\3_acmextensionsconfig_xml_copy.png /f 
del help\assets\offline-api-based-processing.png /f 
del help\assets\meta-model.gif /f 
del help\assets\text-create-hyperlink.png /f 
del help\assets\email_client.png /f 
del help\assets\analytics_config.jpg /f 
del help\assets\ddxRef.pdf /f 
del help\assets\aftia-conversion-progress.jpg /f 
del help\assets\cc-dashboard.png /f 
del help\assets\component_toolbar_table_row_new.png /f 
del help\assets\highlighttextagentui.png /f 
del help\assets\1-3.png /f 
del help\assets\synchronizecontentfrommasterchannel.png /f 
del help\assets\2configmanager.png /f 
del help\assets\delete-1.png /f 
del help\assets\saveasdraft.png /f 
del help\assets\screen_shot_2018-03-09at155516copy.png /f 
del help\assets\typical-architecture.png /f 
del help\assets\mortgage-plans.png /f 
del help\assets\showpreview.png /f 
del help\assets\updated-policy.png /f 
del help\assets\upgrade-jboss.pdf /f 
del help\assets\5_letteroutput.png /f 
del help\assets\statictableproperties.png /f 
del help\assets\visualtopclassic.png /f 
del help\assets\us-web-standards.png /f 
del help\assets\crxsubmitprop.png /f 
del help\assets\cmmetapropertiesoverlaynode.png /f 
del help\assets\object_subform_flowed_new.png /f 
del help\assets\letter_tab_new.png /f 
del help\assets\geolocation.png /f 
del help\assets\simple-author-publish-topology.png /f 
del help\assets\review-and-correct.png /f 
del help\assets\create_ic_print_master_web_new.png /f 
del help\assets\sign-block.png /f 
del help\assets\request-attribute.png /f 
del help\assets\visualleft.png /f 
del help\assets\sharepoint-ifilter-doc-security.pdf /f 
del help\assets\welcome_benefits_handbook.png /f 
del help\assets\job-application-form.png /f 
del help\assets\document-security-offerings.png /f 
del help\assets\agent_ui_email-1.png /f 
del help\assets\aem-forms-document-security-.png /f 
del help\assets\service-configuration-basic.png /f 
del help\assets\cc-analytics.png /f 
del help\assets\rule-editor-ui-1.png /f 
del help\assets\right_circle_cta_new.png /f 
del help\assets\4_highlightmoduleincontent-1.png /f 
del help\assets\gen-settings.png /f 
del help\assets\properties.png /f 
del help\assets\add-components-list1.png /f 
del help\assets\forms_designer_subform.png /f 
del help\assets\cminworkspace.png /f 
del help\assets\analytics_configuration.png /f 
del help\assets\loans3.png /f 
del help\assets\install-turnkey.pdf /f 
del help\assets\expense-report-on-mobile.png /f 
del help\assets\create_first_ic_web_template_new.png /f 
del help\assets\action7.png /f 
del help\assets\1_selectletter.png /f 
del help\assets\form-preview-mobile.gif /f 
del help\assets\email.png /f 
del help\assets\create-a-workflow-pdf2.png /f 
del help\assets\change_font_after.png /f 
del help\assets\redo-undo.png /f 
del help\assets\sarahrosejoiningletteremail.png /f 
del help\assets\upload-scr-err.png /f 
del help\assets\action-tool-bar.png /f 
del help\assets\headersontheleft.png /f 
del help\assets\line_chart_web_new.png /f 
del help\assets\toolbar1.png /f 
del help\assets\start_of_adp_form.png /f 
del help\assets\analytics_recommendation.jpg /f 
del help\assets\weretail_schema_new.png /f 
del help\assets\compass.png /f 
del help\assets\date-range.png /f 
del help\assets\highlightselectedmodulesincontentccr.png /f 
del help\assets\create_print_template.gif /f 
del help\assets\prefill_config.png /f 
del help\assets\s1.png /f 
del help\assets\creditcardchartfrequencyfunctioncopy.png /f 
del help\assets\gloriaschedulesinterview.png /f 
del help\assets\clientsdkconfiguration.jpg /f 
del help\assets\analyticsdashboard_callout.png /f 
del help\assets\delete-icon.png /f 
del help\assets\lf_cell_properties.png /f 
del help\assets\marketing-email.png /f 
del help\assets\conversion-workflow.svg /f 
del help\assets\forms_configuration.png /f 
del help\assets\gloria-inbox.png /f 
del help\assets\3_clientsdkconfiguration.png /f 
del help\assets\img8.png /f 
del help\assets\confirm_new_contact.png /f 
del help\assets\visualtop.png /f 
del help\assets\02-aem-forms-architecture_large.jpg /f 
del help\assets\printweb_2-3.png /f 
del help\assets\usage_charges_rule_editor.png /f 
del help\assets\master_content.png /f 
del help\assets\3_repeat_dialog.png /f 
del help\assets\pagebreakbeforeafter.png /f 
del help\assets\explicitpagebreak.png /f 
del help\assets\3_hoverhandle.png /f 
del help\assets\tnc-1.png /f 
del help\assets\enable_sorting_new-1.png /f 
del help\assets\create-letter.png /f 
del help\assets\form-on-mobile.png /f 
del help\assets\preview.png /f 
del help\assets\ruleeditorfdm.png /f 
del help\assets\table_ic_web.png /f 
del help\assets\update-shipping-address.png /f 
del help\assets\recommended-topology.png /f 
del help\assets\start1_new.png /f 
del help\assets\properties_odata_cloud_service.jpg /f 
del help\assets\as_assembler_fragment_assy_assembled.png /f 
del help\assets\aftia-afc-production.jpg /f 
del help\assets\johndoejoiningletterattachandsend.png /f 
del help\assets\structure_configure_policy.png /f 
del help\assets\day_cq_mail_service.jpg /f 
del help\assets\data_model_objects.png /f 
del help\assets\gloriariosinboxoffer.png /f 
del help\assets\forms-with-clear-borders-scale.png /f 
del help\assets\select_style_ic_web_new.png /f 
del help\assets\slide1-1.png /f 
del help\assets\conflict-form-on-mobile.png /f 
del help\assets\asset.png /f 
del help\assets\lists-with-fields.png /f 
del help\assets\aftia-upload-conversion-settings.jpg /f 
del help\assets\ruleeditorfdm-1.png /f 
del help\assets\run-all-test.png /f 
del help\assets\selectassets.png /f 
del help\assets\service-configuration-advanced.png /f 
del help\assets\ipad-1.png /f 
del help\assets\pastetextmsword-1.png /f 
del help\assets\we-retail-test-suite.png /f 
del help\assets\corporate-card-inbox.png /f 
del help\assets\2-2.png /f 
del help\assets\3_jcrcontentntresource.png /f 
del help\assets\apply_now_link.png /f 
del help\assets\crxstorewithfa.png /f 
del help\assets\insertdmandlf.png /f 
del help\assets\viewcard.png /f 
del help\assets\topology-for-using-forms-osgi-modules.png /f 
del help\assets\5_onmouseoverconditionrule.png /f 
del help\assets\employee-dashboard-1.png /f 
del help\assets\3-1.png /f 
del help\assets\scripting-reference.pdf /f 
del help\assets\exec-light-1.png /f 
del help\assets\erroronright.zip /f 
del help\assets\formeditor.png /f 
del help\assets\create_ic_options_updated_new.png /f 
del help\assets\01-create-first-adaptive-form-hero-image.png /f 
del help\assets\raw-image-with-index.png /f 
del help\assets\gradle_wrapper_properties.png /f 
del help\assets\fdm_associations.gif /f 
del help\assets\0_1_introscreenshot-1.png /f 
del help\assets\employee-dashboard-2.png /f 
del help\assets\documentcontainerproperties.png /f 
del help\assets\snap.png /f 
del help\assets\styleaf.png /f 
del help\assets\formcalc-reference.pdf /f 
del help\assets\aem_web_configuration_console.png /f 
del help\assets\add-component.gif /f 
del help\assets\09-Style-your-adaptive-form_small.png /f 
del help\assets\data-model-object.png /f 
del help\assets\dynamictableproperties.png /f 
del help\assets\saveasdraftdialog_name.png /f 
del help\assets\analytics_report_benefits.jpg /f 
del help\assets\railleftpng.png /f 
del help\assets\search_topbar.png /f 
del help\assets\3configmanager.png /f 
del help\assets\portal.jpg /f 
del help\assets\test_data_model_new.png /f 
del help\assets\filter-1.png /f 
del help\assets\variable.png /f 
del help\assets\data_model_objects_new.png /f 
del help\assets\resume.png /f 
del help\assets\lcoationofrecipientsui.png /f 
del help\assets\install-single-server-websphere.pdf /f 
del help\assets\aftia-conversion-in-progress.jpg /f 
del help\assets\leave-inbox.png /f 
del help\assets\we-finance-insurance-workflow-model.png /f 
del help\assets\view_setting_analytics.jpg /f 
del help\assets\embed-in-aem-sites.png /f 
del help\assets\start-a-new-form.png /f 
del help\assets\ungroup.svg /f 
del help\assets\saveasdraftdialog.png /f 
del help\assets\update_service_properties_new.png /f 
del help\assets\line_chart_web_sum_new.png /f 
del help\assets\listoptions.png /f 
del help\assets\johnjacobsbackgroundcheckinbox.png /f 
del help\assets\insertdmandlf2.png /f 
del help\assets\textbackgroundcolorapplied.png /f 
del help\assets\corporate-card-expense-report-workflow-model.png /f 
del help\assets\libraryaccess.png /f 
del help\assets\test-data-model-2.png /f 
del help\assets\analyticsreport.png /f 
del help\assets\aem_forms_console_new.png /f 
del help\assets\asset-sync-error-message.png /f 
del help\assets\ppoverview.png /f 
del help\assets\img4.png /f 
del help\assets\exec-light.png /f 
del help\assets\calculatorconfigurepanel.png /f 
del help\assets\usage_charges_rule_editor_new.png /f 
del help\assets\aem6forms_panel-pdf.png /f 
del help\assets\configure_columns.jpg /f 
del help\assets\maximize_icon.svg /f 
del help\assets\sarahroseinterviewemail.png /f 
del help\assets\create_ic_print_master_new-1.png /f 
del help\assets\logconfig-1.png /f 
del help\assets\logo-1.png /f 
del help\assets\insurance-contact-letter.png /f 
del help\assets\insurance-ssn.png /f 
del help\assets\default_toolbar_layout.png /f 
del help\assets\adaptive_form.png /f 
del help\assets\theme-custom-component.png /f 
del help\assets\lcoationofrecipientsui-1.png /f 
del help\assets\logo.png /f 
del help\assets\templatescorrespondence.png /f 
del help\assets\start1.png /f 
del help\assets\goodfunctions.jar.zip /f 
del help\assets\home_mortgage_application_walkthrough.png /f 
del help\assets\statement-email.png /f 
del help\assets\search.png /f 
del help\assets\header-style.png /f 
del help\assets\records.json /f 
del help\assets\recipientstab-1.png /f 
del help\assets\convert.png /f 
del help\assets\create_data_binding_table_new.png /f 
del help\assets\1_tapnameoftestcase.png /f 
del help\assets\create_child_property_float.png /f 
del help\assets\4_createrule.png /f 
del help\assets\create-a-workflow3-pdf.png /f 
del help\assets\paragrapheditingtoolbar-1.png /f 
del help\assets\adaptive-form-with-survey-theme.png /f 
del help\assets\editicon.png /f 
del help\assets\gradle_unsupported_version.png /f 
del help\assets\customtoolbarlayoutdemo.zip /f 
del help\assets\paragrapheditingtoolbar.png /f 
del help\assets\variablespane.png /f 
del help\assets\nestedlf.png /f 
del help\assets\test_service.png /f 
del help\assets\dynamics_authentication_settings.png /f 
del help\assets\msdynamicsrecord.png /f 
del help\assets\conflict-approved.png /f 
del help\assets\toolbar3.png /f 
del help\assets\aftia-configuration-options.jpg /f 
del help\assets\microsoft-badge-icon.png /f 
del help\assets\upgrade-weblogic-livecycle.pdf /f 
del help\assets\code-editor.png /f 
del help\assets\dd.jpeg /f 
del help\assets\template_editor_initial_content_new.png /f 
del help\assets\select_data_model_object_services_new.png /f 
del help\assets\auto-insurance-application-walkthrough.png /f 
del help\assets\auth-layt.png /f 
del help\assets\textbackgroundcolor-1.png /f 
del help\assets\aem6forms_error_alert.png /f 
del help\assets\04-create-form-data-model-main.png /f 
del help\assets\chartprintchannel.png /f 
del help\assets\aem6forms_search.png /f 
del help\assets\lentcontent.png /f 
del help\assets\letterbackgroundcolor.png /f 
del help\assets\configure-icon.svg /f 
del help\assets\variables_bill_details.png /f 
del help\assets\05-create-form-data-model-main_small.png /f 
del help\assets\img1.png /f 
del help\assets\us_cm_architecture_es3.png /f 
del help\assets\ruleincondition.png /f 
del help\assets\12-publish-your-adaptive-form-_small.png /f 
del help\assets\dirtyaf.png /f 
del help\assets\create_new_process.png /f 
del help\assets\searchfortask.png /f 
del help\assets\border-less-tables.png /f 
del help\assets\img9.png /f 
del help\assets\metadata-entry-1.png /f 
del help\assets\mortgage-application.png /f 
del help\assets\itemsoverlaynode.png /f 
del help\assets\subform_component_designer_new.png /f 
del help\assets\johndoeneedmoreinformation.png /f 
del help\assets\address-1.png /f 
del help\assets\aftia-upload-form.jpg /f 
del help\assets\ultramarine.png /f 
del help\assets\loans1.png /f 
del help\assets\variableinserted.png /f 
del help\assets\goodfunctions.zip /f 
del help\assets\intial-count.png /f 
del help\assets\designer-samples.pdf /f 
del help\assets\dialog.png /f 
del help\assets\theme-editor-1.png /f 
del help\assets\edit-argument.png /f 
del help\assets\export-last-run-details.png /f 
del help\assets\ref1.png /f 
del help\assets\urbane-1.png /f 
del help\assets\test_service_new.png /f 
del help\assets\2-1.png /f 
del help\assets\using-autosave-freq-07-1.png /f 
del help\assets\pastetextmsword.png /f 
del help\assets\shiiping-address-retrieval.png /f 
del help\assets\enable-analytics-1.png /f 
del help\assets\break.png /f 
del help\assets\wegov_forms_package-1.jpg /f 
del help\assets\text_document_fragments.gif /f 
del help\assets\use-pic.png /f 
del help\assets\leave-form-on-mobile.png /f 
del help\assets\card-form.png /f 
del help\assets\adobe_sign_link.png /f 
del help\assets\dscsample.zip /f 
del help\assets\use_crx_asset.png /f 
del help\assets\collapsing_panels_image.png /f 
del help\assets\save-operation-service.png /f 
del help\assets\drag-drop-1.png /f 
del help\assets\update_service_properties.png /f 
del help\assets\fp-grid-viw.png /f 
del help\assets\workflow_insurance.png /f 
del help\assets\bill_summary_static_variables_new.png /f 
del help\assets\home-page.png /f 
del help\assets\1_selecttext.png /f 
del help\assets\geographic_settings.png /f 
del help\assets\ic-web-version.png /f 
del help\assets\save-as-draft-save-operation.png /f 
del help\assets\variable_bill_details_new.png /f 
del help\assets\migrate-and-syncronize.png /f 
del help\assets\sites_analysis.jpg /f 
del help\assets\usgov.png /f 
del help\assets\cancel_inheritance_web_channel.png /f 
del help\assets\default-email-template.png /f 
del help\assets\ds_settings_new.png /f 
del help\assets\ic_web_content_tree.png /f 
del help\assets\conflict-inbox.png /f 
del help\assets\analytics_recommendations.jpg /f 
del help\assets\designer-quickstart.pdf /f 
del help\assets\aftia-health-confirmation.jpg /f 
del help\assets\placeholder_elements_in_text.png /f 
del help\assets\installing-workbench.png /f 
del help\assets\add_argument_association.png /f 
del help\assets\expandededitruledialog.png /f 
del help\assets\retrieve-information.gif /f 
del help\assets\add_association.png /f 
del help\assets\agent_ui_email_new.png /f 
del help\assets\check-typex75.gif /f 
del help\assets\cu_customized_workspace_example.png /f 
del help\assets\george_lang.png /f 
del help\assets\prepare-install-cluster.pdf /f 
del help\assets\insurance-policy-details.png /f 
del help\assets\create_rules_caption.gif /f 
del help\assets\1_overlaynode_css.png /f 
del help\assets\insurance-welcome-kit-email.png /f 
del help\assets\win-dir.png /f 
del help\assets\as_intro_pdfsfrombookmarks.png /f 
del help\assets\cu_manager_view.png /f 
del help\assets\2_addddpropertiesbasic.png /f 
del help\assets\createcorrespondencecreated.png /f 
del help\assets\fdm_mysql_data_source.png /f 
del help\assets\aem6forms_edit.png /f 
del help\assets\component_toolbar_group_objects_new.png /f 
del help\assets\jcrcontentproperties.png /f 
del help\assets\lists-containing-choice-groups.png /f 
del help\assets\layout_fragment_print_new.png /f 
del help\assets\usingoutput_modified.png /f 
del help\assets\exec.png /f 
del help\assets\insurance-welcome-kit.png /f 
del help\assets\createconditionassetsadd.png /f 
del help\assets\as_assembler_xdpassembly.png /f 
del help\assets\loans2.png /f 
del help\assets\form_data_model_callouts_new.png /f 
del help\assets\test-read-model.png /f 
del help\assets\upgrade-jboss-livecycle-es3.pdf /f 
del help\assets\default_toolbar_actions.png /f 
del help\assets\simplification-of-authoring-forms-and-documents_hero-image_2.png /f 
del help\assets\bill_summary_static_variables.png /f 
del help\assets\save-as-draft.png /f 
del help\assets\09-Style-your-adaptive-form.png /f 
del help\assets\default-adaptive-form.png /f 
del help\assets\webchanneltemplate.png /f 
del help\assets\aem-forms-console.png /f 
del help\assets\offline-batch-processing-via-watched-folders.png /f 
del help\assets\root_subform_print_template_new.png /f 
del help\assets\ruleeditoricon.png /f 
del help\assets\apache_configuration_new.png /f 
del help\assets\gradle_plugin_compatibility.png /f 
del help\assets\cross.png /f 
del help\assets\wealth-management-prospectus-walkthrough.png /f 
del help\assets\mob1.png /f 
del help\assets\creditcardchartsumfunctioncopy.png /f 
del help\assets\bulleteditingtoolbar.png /f 
del help\assets\need-more-info.png /f 
del help\assets\aem6forms_tableedit.png /f 
del help\assets\customerrormanager-1.0-snapshot.zip /f 
del help\assets\corporate-card-approved.png /f 
del help\assets\2_cmuserroot_newnode.png /f 
del help\assets\01-aem-forms-architecture.jpg /f 
del help\assets\aftia-update-data-source.jpg /f 
del help\assets\updated-adaptive-form.png /f 
del help\assets\advancedediting.png /f 
del help\assets\insurance-inbox-grios.png /f 
del help\assets\employee-dashboard-3.png /f 
del help\assets\example.png /f 
del help\assets\5_repeateditremove.png /f 
del help\assets\ab-test-report-1.png /f 
del help\assets\perm_workspace_user.png /f 
del help\assets\custom-theme.png /f 
del help\assets\mws_startpoint_select_option.png /f 
del help\assets\ds_settings.png /f 
del help\assets\create_first_ic_doc_fragments_new.png /f 
del help\assets\install-cluster-jboss.pdf /f 
del help\assets\create_new_appl.png /f 
del help\assets\chart.png /f 
del help\assets\recaptcha_new.png /f 
del help\assets\prepare-upgrade.pdf /f 
del help\assets\scanned-form.jpg /f 
del help\assets\step2.png /f 
del help\assets\2_createnodedownloadflatpdf.png /f 
del help\assets\feedmanagement.png /f 
del help\assets\exec-1.png /f 
del help\assets\payment-adaptive-form.png /f 
del help\assets\store_and_email_submit_action_dialog.jpg /f 
del help\assets\aftia-conversion-complete.jpg /f 
del help\assets\3_addddpropertiesadvanced.png /f 
del help\assets\write-default.png /f 
del help\assets\architecture.png /f 
del help\assets\android-folder.png /f 
del help\assets\11-test-your-adaptive-form.png /f 
del help\assets\createconditionscreenassetsaddedannotated.png /f 
del help\assets\balancedleft.png /f 
del help\assets\5_acmextensionsconfig_xml.png /f 
del help\assets\name-1.png /f 
del help\assets\footer-node-properties-1.png /f 
del help\assets\aftia-conversion-settings-2.jpg /f 
del help\assets\employee-self-service-reference-site.png /f 
del help\assets\save-as-draft-get-operation.png /f 
del help\assets\createapppackageswizard1.png /f 
del help\assets\gen_question_b_20.png /f 
del help\assets\candidate-shortlist.png /f 
del help\assets\edit_properties_get_details_new.png /f 
del help\assets\aftia-review-conversion.jpg /f 
del help\assets\edit_sample_data_new.png /f 
del help\assets\img14.png /f 
del help\assets\basicpropertieswebchannel.png /f 
del help\assets\customer_details_static_text_fdm.png /f 
del help\assets\aem_forms_ui.png /f 
del help\assets\template-edit-initial-content-1.png /f 
del help\assets\start-conversion-dialog.png /f 
del help\assets\cmppr-1.png /f 
del help\assets\sync-conflict.png /f 
del help\assets\selecting_form.png /f 
del help\assets\gloriariosapproves.png /f 
del help\assets\step.png /f 
del help\assets\gloriariosselectcandidate.png /f 
del help\assets\aftia-converted-adaptive-form-2.jpg /f 
del help\assets\we-finance-employee-recruiting-workflow.png /f 
del help\assets\letterwithsignature.png /f 
del help\assets\edit-draft-app.png /f 
del help\assets\add_association_customer_bills_new.png /f 
del help\assets\apache_configuration.png /f 
del help\assets\default-render-form.png /f 
del help\assets\6_repeatoutputpreview.png /f 
del help\assets\edit_properties_get_details.png /f 
del help\assets\exportpackage_1431709897770.cmp.zip /f 
del help\assets\03-create-adaptive-form-main-image_small.png /f 
del help\assets\create-a-workflow-cmb.png /f 
del help\assets\conrad-inbox.png /f 
del help\assets\contentmodulefocus.png /f 
del help\assets\usage_charges_rule_all.png /f 
del help\assets\img11.png /f 
del help\assets\img12.png /f 
del help\assets\component-categories.png /f 
del help\assets\html-ws.png /f 
del help\assets\default-fdm.png /f 
del help\assets\new_contact_approval.png /f 
del help\assets\cmmetadatapropertiescreatenode.png /f 
del help\assets\page-viewer-web-part-box-in-microsoft-office-sharepoint-server.png /f 
del help\assets\camila_santos.png /f 
del help\assets\4_editconditionremoveconditionpopup.png /f 
del help\assets\drag-drop.png /f 
del help\assets\path1.png /f 
del help\assets\custom_action_available_in_toolbar.png /f 
del help\assets\autosave-flow.png /f 
del help\assets\content_tree_all_panels_new.png /f 
del help\assets\leave-approved.png /f 
del help\assets\submit-is-clicked.png /f 
del help\assets\customer_details_static_text_new.png /f 
del help\assets\iconeditselectedcontent.png /f 
del help\assets\customfieldappearinginmainproperties.png /f 
del help\assets\treeexpandall.png /f 
del help\assets\sara-rose-statement.png /f 
del help\assets\get-operation-service.png /f 
del help\assets\sorting_ascending_new-1.png /f 
del help\assets\signer-details-1.png /f 
del help\assets\recipientstab.png /f 
del help\assets\close-filter.png /f 
del help\assets\new-node-custom-component.png /f 
del help\assets\aftia-select-fdm.jpg /f 
del help\assets\slide1.png /f 
del help\assets\shaded-box-patterns.png /f 
del help\assets\us_cm_generate.png /f 
del help\assets\career-page.png /f 
del help\assets\insert.png /f 
del help\assets\allowed_components_af.png /f 
del help\assets\footer-node.png /f 
del help\assets\samll_362274_dc_february_launch_press_items_cloud_signature.png /f 
del help\assets\benefits-of-platinum-card.png /f 
del help\assets\aftia-accessibility.jpg /f 
del help\assets\e_reviewmode_properties_n.png /f 
del help\assets\aftia-wefinance-afc-prod.jpg /f 
del help\assets\grios-inbox.png /f 
del help\assets\aftia-ultramarine-theme.jpg /f 
del help\assets\custom-configuration-parameters2.png /f 
del help\assets\we-finance-employee-recruiting-post-interview-workflow.png /f 
del help\assets\hammer-icon.svg /f 
del help\assets\12_applicationmanagementlc.png /f 
del help\assets\df_unbound_variable_new.png /f 
del help\assets\uninstall_wegov_forms_package.jpg /f 
del help\assets\day_cq_wcm_filter.jpg /f 
del help\assets\pastetexteditablemodule.png /f 
del help\assets\custom_layout_new.png /f 
del help\assets\sarahroseemail.png /f 
del help\assets\we-finance-home-2.png /f 
del help\assets\submit_adaptive_form.png /f 
del help\assets\01.png /f 
del help\assets\see-the-guide-sm.png /f 
del help\assets\3_pagecontent.png /f 
del help\assets\aftia-full-admin-access.jpg /f 
del help\assets\new_columns_available.jpg /f 
del help\assets\default_email_template_metadata_new.png /f 
del help\assets\html5_forms_best_practices_reference_card.pdf /f 
del help\assets\coloured-form.png /f 
del help\assets\add-custom-rule-1.png /f 
del help\assets\update-operation-service.png /f 
del help\assets\create-user.png /f 
del help\assets\custompropertyinlistview.png /f 
del help\assets\action9.png /f 
del help\assets\save-and-convert.png /f 
del help\assets\ds_settings_service_new.png /f 
del help\assets\customer_details_df2_new.png /f 
del help\assets\select_style_ic_web.png /f 
del help\assets\refresh_forms_di.png /f 
del help\assets\portal-drafts.png /f 
del help\assets\upgrade-path-osgi.png /f 
del help\assets\createapppackages.png /f 
del help\assets\chart_agentproperties.png /f 
del help\assets\configure-the-watched-folder-pdf.png /f 
del help\assets\aem-fp-db-integration-sample-pkg-6.1.2.zip /f 
del help\assets\newreportsuite.png /f 
del help\assets\tnc-scribble-1.png /f 
del help\assets\ruleeditor.png /f 
del help\assets\editnextmoduleccr.png /f 
del help\assets\ab-test-report-4.png /f 
del help\assets\statement-details.png /f 
del help\assets\2.png /f 
del help\assets\af_properties.png /f 
del help\assets\johnjacobs.png /f 
del help\assets\johndoescheduleinterview.png /f 
del help\assets\newreportsuite_new.png /f 
del help\assets\sarahrosejoininglettersign.png /f 
del help\assets\aem6forms_eye_viewon.png /f 
del help\assets\analytics-report.png /f 
del help\assets\6_assetcomposerbuildingblockbundle.png /f 
del help\assets\form_data_model_callouts.png /f 
del help\assets\adaptive-form-with-headers-and-footers.png /f 
del help\assets\workflow_aem_gov_2.png /f 
del help\assets\summary_charges_static_fdm.png /f 
del help\assets\icondelete.png /f 
del help\assets\itemscreatenode.png /f 
del help\assets\configure_services_customer.png /f 
del help\assets\panel-report-detailed.png /f 
del help\assets\checkmark.png /f 
del help\assets\analytics_report_data.jpg /f 
del help\assets\2_enterdata.png /f 
del help\assets\component_toolbar_table1.png /f 
del help\assets\workflow.gif /f 
del help\assets\selectcontentapplyrule.png /f 
del help\assets\sample_package.zip /f 
del help\assets\gloriainbox.png /f 
del help\assets\cacheworkflow.png /f 
del help\assets\aftia-create-new-integration.jpg /f 
del help\assets\edit_sample_data.png /f 
del help\assets\additionalinformation2.png /f 
del help\assets\data_display_patterns_fields.jpg /f 
del help\assets\repeatwitincondition.png /f 
del help\assets\aem-forms-tools.png /f 
del help\assets\custom.png /f 
del help\assets\johndoejoiningletterinbox.png /f 
del help\assets\creditcarddatalinechartcopy.png /f 
del help\assets\search-panel.png /f 
del help\assets\aftia-pdf-forms.jpg /f 
del help\assets\income-1.png /f 
del help\assets\1_createnode_cmuserroot.png /f 
del help\assets\aem_forms_tools_new.png /f 
del help\assets\aftia-converted-adaptive-form.jpg /f 
del help\assets\4_deleteelement.png /f 
del help\assets\employee-dashboard.png /f 
del help\assets\line_chart_web_functions_frequency_new.png /f 
del help\assets\sarah-sign-1.png /f 
del help\assets\as_document_assembly.png /f 
del help\assets\nested-lists.png /f 
del help\assets\add_association_argument_new.png /f 
del help\assets\new-state-theme.png /f 
del help\assets\add_argument_association_new.png /f 
del help\assets\fdm_mysql_data_source_new.png /f 
del help\assets\img7.png /f 
del help\assets\1_2_createanelement.png /f 
del help\assets\alignmenttoolbar.png /f 
del help\assets\style-option.png /f 
del help\assets\emptycondition.png /f 
del help\assets\sample-transaction-report-author-1.png /f 
del help\assets\img5.png /f 
del help\assets\attachfiles.png /f 
del help\assets\inbox.png /f 
del help\assets\digital_signatures.png /f 
del help\assets\step1.png /f 
del help\assets\form_model_xfa_associate.png /f 
del help\assets\step3.png /f 
del help\assets\aftia-conversion-settings.jpg /f 
del help\assets\slingfolder.png /f 
del help\assets\createcondition.png /f 
del help\assets\connecteddevice.png /f 
del help\assets\sign-multiple-forms.jpg /f 
del help\assets\johndoeinbox.png /f 
del help\assets\app_store.png /f 
del help\assets\edit-link-component.png /f 
del help\assets\5_deconstructingaletter.png /f 
del help\assets\submit-for-re-evaluation.png /f 
del help\assets\export.png /f 
del help\assets\print_xdp_template_subform.png /f 
del help\assets\allowed_components_af_new.png /f 
del help\assets\model-refresh.png /f 
del help\assets\bulkapproval.png /f 
del help\assets\emp-history-1.png /f 
del help\assets\openagentiui.png /f 
del help\assets\attch.png /f 
del help\assets\create_ic_print_master_web_new-1.png /f 
del help\assets\upgrade-checklist.pdf /f 
del help\assets\sarah-enrollment-details.png /f 
del help\assets\johnjacobsbackgroundcheckgoahead.png /f 
del help\assets\read-updated.png /f 
del help\assets\gen-settings-1.png /f 
del help\assets\auto-insurance-workflow.png /f 
del help\assets\sample-transaction-report-author.png /f 
del help\assets\sarahfiosform.png /f 
del help\assets\aftia-admin-user-access.jpg /f 
del help\assets\using-autosave-freq-07.png /f 
del help\assets\aem6forms_delete2.png /f 
del help\assets\af_submission_properties.png /f 
del help\assets\bullet_checkmark.png /f 
del help\assets\createruledialog.png /f 
del help\assets\change_font_before.png /f 
del help\assets\lf_dragdrop.png /f 
del help\assets\sampletestpackage.zip /f 
del help\assets\current-emp-1.png /f 
del help\assets\2configmanager-1.png /f 
del help\assets\oauth_config.png /f 
del help\assets\hierarchy-1.png /f 
del help\assets\aya_tan_new-1.png /f 
del help\assets\beryl-1.png /f 
del help\assets\aftia-enrollment-fdm.jpg /f 
del help\assets\print_xdp_template_subform_new.png /f 
del help\assets\welcome-kit-for-sara.png /f 
del help\assets\aftia-user-management.jpg /f 
del help\assets\interactive-communication-charts.png /f 
del help\assets\customizationdropdownvaluescrxde.png /f 
del help\assets\chart_properties_print_new.png /f 
del help\assets\ds_settings_1.png /f 
del help\assets\aem6forms_close.svg_w24.png /f 
del help\assets\advancedediting-1.png /f 
del help\assets\09-style-your-adaptive-form-small.png /f 
del help\assets\1_1renderwithoutrepeat.png /f 
del help\assets\layout_fragment_print_repeat.png /f 
del help\assets\1cofigmanager.png /f 
del help\assets\chart-2.png /f 
del help\assets\insurance-newsletter.png /f 
del help\assets\gloria-sends-assessment.png /f 
del help\assets\aem6forms_sync.png /f 
del help\assets\upgrade-websphere-livecycle.pdf /f 
del help\assets\search_forms_assets.png /f 
del help\assets\1-4.png /f 
del help\assets\report_suites.jpg /f 
del help\assets\retake.png /f 
del help\assets\uploaded-documents.png /f 
del help\assets\adaptive-form-with-all-the-components.png /f 
del help\assets\content_tree_grouping.png /f 
del help\assets\browse.png /f 
del help\assets\geographicallocationcreatenode.png /f 
del help\assets\printweb_2-1.png /f 
del help\assets\viewlist.png /f 
del help\assets\select_data_model_objs_services.png /f 
del help\assets\content_tree_root_panel.png /f 
del help\assets\getall-operation-service.png /f 
del help\assets\interactive_communication-01.jpg /f 
del help\assets\geometrixx-outdoors.png /f 
del help\assets\variable_bill_details_static_text.png /f 
del help\assets\recaptcha.png /f 
del help\assets\draft-submission.png /f 
del help\assets\form-fields-with-far-away-captions.png /f 
del help\assets\urbane.png /f 
del help\assets\create_hyperlink_table_new.png /f 
del help\assets\2_repeat_selecttext.png /f 
del help\assets\edit-list.png /f 
del help\assets\cmmetadatapropertiesoverlaynode.png /f 
del help\assets\start3_new.png /f 
del help\assets\mortgage-form-on-mobile.png /f 
del help\assets\mysql_fdm_new.png /f 
del help\assets\footer-node-properties.png /f 
del help\assets\contact-info-1.png /f 
del help\assets\custom-widgets.jpg /f 
del help\assets\mysql_fdm.png /f 
del help\assets\aftia-technical-account-configuration.jpg /f 
del help\assets\5_jcrdata.png /f 
del help\assets\test-write-model.png /f 
del help\assets\03-create-adaptive-form-main-image_small_new.png /f 
del help\assets\aem-forms-JEE-services-reference.pdf /f 
del help\assets\6_downloadflatpdf.png /f 
del help\do-not-localize\aem_forms_workflow.png /f 
del help\do-not-localize\as_batesnumber.png /f 
del help\do-not-localize\offers.png /f 
del help\do-not-localize\toolbar.png /f 
del help\do-not-localize\toolbarselection.png /f 
del help\do-not-localize\correspondence-management.png /f 
del help\do-not-localize\listingtoolbar.png /f 
del help\do-not-localize\contentoptionsdocfragments.png /f 
del help\do-not-localize\4th-draft.gif /f 
del help\do-not-localize\component_toolbar_labels_new.png /f 
del help\do-not-localize\13-publish-your-adaptive-form-small.png /f 
del help\do-not-localize\document-security-typical-environment.png /f 
del help\do-not-localize\default_email_template_new.png /f 
del help\do-not-localize\osgi-upgrade-path.png /f 
del help\do-not-localize\document_security_architecture.png /f 
del help\do-not-localize\data-integeration-1.png /f 
del help\do-not-localize\1_ddproperties.png /f 
del help\do-not-localize\3rd-draft.gif /f 
del help\do-not-localize\paragraphtoolbar-1.png /f 
del help\do-not-localize\document-services.png /f 
del help\do-not-localize\10-test-your-adaptive-form.png /f 
del help\do-not-localize\form-preview-mobile.gif /f 
del help\do-not-localize\customized-email.png /f 
del help\do-not-localize\listtoolbar.png /f 
del help\do-not-localize\jee-upgrade-6-5.png /f 
del help\do-not-localize\layout-02.png /f 
del help\do-not-localize\osgi-upgrade.png /f 
del help\do-not-localize\paragraphtoolbar.png /f 
del help\do-not-localize\mobile_form_on_an_ipad_date_14.png /f 
del help\do-not-localize\default-email-template.png /f 
del help\do-not-localize\responsive-panel-container.png /f 
del help\do-not-localize\best-practices_reference_card.png /f 
del help\do-not-localize\document-security-server_topology.png /f 
del help\do-not-localize\08-style_your_adaptiveformmain.png /f 
del help\do-not-localize\jee-upgrade-6-4.png /f 
del help\do-not-localize\fonttoolbar.png